name: Shell commands
on: [push] # event
jobs: # 1 job
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps: # 2 étapes
      - name: echo a string
        run: echoo "Hello world"
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l